Brandy Larramore DA10 Capstone

In [1]:
import pandas as pd

In [2]:
file_path_i = '../data/income2022data.csv'
income_data = pd.read_csv(file_path_i, skiprows=[0])
income_data.head

<bound method NDFrame.head of           Geography                  Geographic Area Name  \
0         0100000US                         United States
1    0500000US01003               Baldwin County, Alabama
2    0500000US01015               Calhoun County, Alabama
3    0500000US01043               Cullman County, Alabama
4    0500000US01049                DeKalb County, Alabama
..              ...                                   ...
844  0500000US72113          Ponce Municipio, Puerto Rico
845  0500000US72127       San Juan Municipio, Puerto Rico
846  0500000US72135       Toa Alta Municipio, Puerto Rico
847  0500000US72137       Toa Baja Municipio, Puerto Rico
848  0500000US72139  Trujillo Alto Municipio, Puerto Rico

     Estimate!!Households!!Total  Margin of Error!!Households!!Total  \
0                      129870928                              136261
1                          98854                                3781
2                          45701                                1562
3                          35966                                1274
4                          26459                                1114
..                           ...                                 ...
844                        54689                                1849
845                       158386                                3330
846                        23703                                1012
847                        28722                                1482
848                        29677                                1065

     Estimate!!Households!!Total!!Less than $10,000  \
0                                               5.5
1                                               5.6
2                                               9.1
3                                               7.3
4                                               9.5
..                                              ...
844                                            30.9
845                                            25.0
846                                             9.8
847                                            17.8
848                                            20.7

     Margin of Error!!Households!!Total!!Less than $10,000  \
0                                                  0.1
1                                                  1.8
2                                                  2.4
3                                                  2.6
4                                                  3.0
..                                                 ...
844                                                3.1
845                                                2.1
846                                                3.5
847                                                3.5
848                                                5.0

     Estimate!!Households!!Total!!$10,000 to $14,999  \
0                                                3.7
1                                                3.8
2                                                6.0
3                                                4.7
4                                                5.2
..                                               ...
844                                             13.3
845                                              8.8
846                                              6.4
847                                              6.8
848                                              6.0

     Margin of Error!!Households!!Total!!$10,000 to $14,999  \
0                                                  0.1
1                                                  1.5
2                                                  2.2
3                                                  2.0
4                                                  2.0
..                                                 ...
844                                                2.5
845                                                1.2
846                                                2.6
847                                                2.4
848                                                3.5

     Estimate!!Households!!Total!!$15,000 to $24,999  \
0                                                6.8
1                                                9.7
2                                                7.3
3                                               11.4
4                                               12.8
..                                               ...
844                                             16.8
845                                             16.0
846                                             17.8
847                                             20.4
848                                             15.4

     Margin of Error!!Households!!Total!!$15,000 to $24,999  ...  \
0                                                  0.1       ...
1                                                  2.1       ...
2                                                  2.4       ...
3                                                  3.6       ...
4                                                  3.2       ...
..                                                 ...       ...
844                                                2.3       ...
845                                                1.6       ...
846                                                4.2       ...
847                                                4.1       ...
848                                                5.1       ...

     Margin of Error!!Nonfamily households!!Median income (dollars)  \
0                                                  166
1                                                 5248
2                                                 4724
3                                                 6018
4                                                 3339
..                                                 ...
844                                               1589
845                                               1486
846                                               8681
847                                               4985
848                                               3607

     Estimate!!Nonfamily households!!Mean income (dollars)  \
0                                                66351
1                                                47800
2                                                39522
3                                                54104
4                                                30442
..                                                 ...
844                                              18803
845                                              31619
846                                              32896
847                                              24591
848                                              26817

     Margin of Error!!Nonfamily households!!Mean income (dollars)  \
0                                                  245
1                                                 6231
2                                                 7197
3                                                12087
4                                                 4103
..                                                 ...
844                                               2311
845                                               2438
846                                               8259
847                                               3734
848                                               9344

     Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months  \
0                                                  (X)
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
844                                                (X)
845                                                (X)
846                                                (X)
847                                                (X)
848                                                (X)

     Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months  \
0                                                  (X)
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
844                                                (X)
845                                                (X)
846                                                (X)
847                                                (X)
848                                                (X)

     Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months  \
0                                                  (X)
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
844                                                (X)
845                                                (X)
846                                                (X)
847                                                (X)
848                                                (X)

     Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months  \
0                                                  (X)
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
844                                                (X)
845                                                (X)
846                                                (X)
847                                                (X)
848                                                (X)

     Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months  \
0                                                 32.7
1                                                 31.2
2                                                 35.6
3                                                 38.3
4                                                 25.9
..                                                 ...
844                                               23.1
845                                               29.5
846                                               25.9
847                                               26.1
848                                               38.2

     Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months  \
0                                                  (X)
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
844                                                (X)
845                                                (X)
846                                                (X)
847                                                (X)
848                                                (X)

     Unnamed: 130
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
..            ...
844           NaN
845           NaN
846           NaN
847           NaN
848           NaN

[849 rows x 131 columns]>

In [3]:
income_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 849 entries, 0 to 848
Columns: 131 entries, Geography to Unnamed: 130
dtypes: float64(44), int64(16), object(71)
memory usage: 869.0+ KB

In [4]:
income_data.head(1)

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to $24,999",...,Margin of Error!!Nonfamily households!!Median income (dollars),Estimate!!Nonfamily households!!Mean income (dollars),Margin of Error!!Nonfamily households!!Mean income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 130
0,0100000US,United States,129870928,136261,5.5,0.1,3.7,0.1,6.8,0.1,...,166,66351,245,(X),(X),(X),(X),32.7,(X),NaN

In [5]:
income_data['FIPS'] = income_data['Geography'].str[-5:] #getting the last 5 numbers which is the FIPS code
income_data.head(10)

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to $24,999",...,Estimate!!Nonfamily households!!Mean income (dollars),Margin of Error!!Nonfamily households!!Mean income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 130,FIPS
0,0100000US,United States,129870928,136261,5.5,0.1,3.7,0.1,6.8,0.1,...,66351,245,(X),(X),(X),(X),32.7,(X),NaN,000US
1,0500000US01003,"Baldwin County, Alabama",98854,3781,5.6,1.8,3.8,1.5,9.7,2.1,...,47800,6231,(X),(X),(X),(X),31.2,(X),NaN,01003
2,0500000US01015,"Calhoun County, Alabama",45701,1562,9.1,2.4,6.0,2.2,7.3,2.4,...,39522,7197,(X),(X),(X),(X),35.6,(X),NaN,01015
3,0500000US01043,"Cullman County, Alabama",35966,1274,7.3,2.6,4.7,2.0,11.4,3.6,...,54104,12087,(X),(X),(X),(X),38.3,(X),NaN,01043
4,0500000US01049,"DeKalb County, Alabama",26459,1114,9.5,3.0,5.2,2.0,12.8,3.2,...,30442,4103,(X),(X),(X),(X),25.9,(X),NaN,01049
5,0500000US01051,"Elmore County, Alabama",34061,981,4.6,1.9,2.9,1.7,5.5,2.1,...,56932,9362,(X),(X),(X),(X),43.9,(X),NaN,01051
6,0500000US01055,"Etowah County, Alabama",39956,1533,4.9,1.7,7.1,2.4,13.1,2.5,...,36838,5415,(X),(X),(X),(X),39.0,(X),NaN,01055
7,0500000US01069,"Houston County, Alabama",42417,1234,7.8,1.3,5.7,1.1,8.9,1.3,...,44779,3924,(X),(X),(X),(X),35.7,(X),NaN,01069
8,0500000US01073,"Jefferson County, Alabama",271877,2948,6.8,0.9,5.6,0.9,8.3,0.9,...,56913,7702,(X),(X),(X),(X),29.7,(X),NaN,01073
9,0500000US01077,"Lauderdale County, Alabama",39021,1359,6.4,2.1,4.8,1.8,9.6,2.3,...,41460,4471,(X),(X),(X),(X),33.3,(X),NaN,01077

In [6]:
column_names = income_data.columns.tolist()

'Geography' in column_names, column_names[:10]

(True,
 ['Geography',
  'Geographic Area Name',
  'Estimate!!Households!!Total',
  'Margin of Error!!Households!!Total',
  'Estimate!!Households!!Total!!Less than $10,000',
  'Margin of Error!!Households!!Total!!Less than $10,000',
  'Estimate!!Households!!Total!!$10,000 to $14,999',
  'Margin of Error!!Households!!Total!!$10,000 to $14,999',
  'Estimate!!Households!!Total!!$15,000 to $24,999',
  'Margin of Error!!Households!!Total!!$15,000 to $24,999'])

In [7]:
file_path_v = '../data/Vaccination_Coverage_among_Adults__18__Years__20240107.csv'
vaccination_data = pd.read_csv(file_path_v)
vaccination_data.head()

,Vaccine,Geography Type,Geography,FIPS,Survey Year,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
0,Tdap,States/Local Areas,Alaska,2,2019,≥18 Years,Overall,43.2,39.4 to 47.1,1606.0
1,Zoster (Shingles),States/Local Areas,Alaska,2,2017,≥60 Years,Overall,40.6,36.3 to 44.8,1259.0
2,Tdap,States/Local Areas,Alaska,2,2016,≥18 Years,Overall,31.9,28.5 to 35.3,1919.0
3,Tdap,States/Local Areas,Alaska,2,2013,≥18 Years,Overall,33.5,31.0 to 36.0,2756.0
4,Tdap,States/Local Areas,Alaska,2,2019,≥18 Years,"White, Non-Hispanic",48.2,44.0 to 52.5,1220.0

In [10]:
income_data['FIPS'] = income_data['FIPS'].astype(str)
vaccination_data['FIPS'] = vaccination_data['FIPS'].astype(str)

In [11]:
common_fips_df = pd.merge(income_data, vaccination_data, on='FIPS', how='inner') #joining them

common_fips = common_fips_df['FIPS'].unique()
print(common_fips)

['10001' '10003' '10005' '11001' '12001' '12005' '12009' '12011' '12015'
 '12017' '12019' '12021' '12023' '12031' '12033' '12035' '12053' '12055'
 '12057' '12061' '12069' '12071' '12073' '12081' '12083' '12085' '12086'
 '12087' '12089' '12091' '12095' '12097' '12099' '12101' '12103' '12105'
 '12107' '12109' '12111' '12113' '12115' '12117' '12119' '12127' '12131'
 '13013' '13015' '13021' '13031' '13045' '13047' '13051' '13057' '13059'
 '13063' '13067' '13073' '13077' '13089' '13095' '13097' '13103' '13113'
 '13115' '13117' '13121' '13127' '13135' '13139' '13151' '13153' '13157'
 '13179' '13185' '13215' '13217' '13223' '13245' '13247' '13255' '13285'
 '13295' '13297' '13313' '15001' '15003' '15007' '15009' '16001' '16005'
 '16019' '16027' '16055' '16083' '17019' '17031' '17037' '17043' '17089'
 '17091' '17093' '17097' '17099' '17111' '17113' '17115' '17119' '17143'
 '17161' '17163' '17167' '17179' '17183' '17197' '17199' '17201' '18003'
 '18005' '18011' '18019' '18035' '18039' '18043' '18053' '18057' '18059'
 '18063' '18067' '18081' '18085' '18089' '18091' '18095' '18097' '18105'
 '18109' '18127' '18141' '18157' '18163' '18167' '18173' '18177' '19013'
 '19049' '19061' '19103' '19113' '19153' '19155' '19163' '19169' '19193'
 '20015' '20045' '20091' '20103' '20161' '20173' '20177' '20209' '21015'
 '21029' '21037' '21047' '21059' '21067' '21093' '21111' '21117' '21145'
 '21151' '21185' '21199' '21227' '22005' '22015' '22017' '22019' '22033'
 '22045' '22051' '22055' '22057' '22063' '22071' '22073' '22079' '22097'
 '22103' '22105' '22109' '23001' '23003' '23005' '23011' '23019' '23031'
 '24001' '24003' '24005' '24009' '24013' '24015' '24017' '24021' '24025'
 '24027' '24031' '24033' '24037' '24043' '24045' '24510' '25001' '25003'
 '25005' '25009' '25011' '25013' '25015' '25017' '25021' '25023' '25025'
 '25027' '26005' '26017' '26021' '26025' '26037' '26045' '26049' '26055'
 '26065' '26067' '26075' '26077' '26081' '26087' '26091' '26093' '26099'
 '26103' '26111' '26115' '26117' '26121' '26125' '26139' '26145' '26147'
 '26155' '26159' '26161' '26163' '27003' '27013' '27019' '27027' '27035'
 '27037' '27053' '27109' '27123' '27131' '27137' '27139' '27141' '27145'
 '27163' '27171' '28033' '28035' '28047' '28049' '28059' '28067' '28073'
 '28075' '28081' '28089' '28121' '29019' '29021' '29031' '29037' '29043'
 '29047' '29051' '29071' '29077' '29095' '29097' '29099' '29165' '29183'
 '29187' '29189' '29510' '30013' '30029' '30031' '30049' '30063' '30111'
 '31055' '31109' '31153' '32003' '32031' '33005' '33009' '33011' '33013'
 '33015' '33017' '34001' '34003' '34005' '34007' '34009' '34011' '34013'
 '34015' '34017' '34019' '34021' '34023' '34025' '34027' '34029' '34031'
 '34033' '34035' '34037' '34039' '34041' '35001' '35013' '35025' '35031'
 '35035' '35043' '35045' '35049' '35061' '36001' '36005' '36007' '36009'
 '36011' '36013' '36015' '36019' '36027' '36029' '36045' '36047' '36053'
 '36055' '36059' '36061' '36063' '36065' '36067' '36069' '36071' '36075'
 '36079' '36081' '36083' '36085' '36087' '36089' '36091' '36093' '36101'
 '36103' '36105' '36109' '36111' '36113' '36117' '36119' '37001' '37019'
 '37021' '37023' '37025' '37027' '37031' '37035' '37037' '37045' '37049'
 '37051' '37057' '37063' '37067' '37069' '37071' '37081' '37085' '37089'
 '37097' '37101' '37105' '37109' '37119' '37125' '37127' '37129' '37133'
 '37135' '37141' '37147' '37151' '37155' '37157' '37159' '37171' '37179'
 '37183' '37191' '37193' '37195' '38015' '38017' '38035' '38101' '39003'
 '39007' '39013' '39017' '39023' '39025' '39029' '39035' '39041' '39043'
 '39045' '39049' '39055' '39057' '39061' '39063' '39085' '39089' '39093'
 '39095' '39099' '39101' '39103' '39109' '39113' '39119' '39133' '39139'
 '39141' '39145' '39151' '39153' '39155' '39157' '39159' '39165' '39169'
 '39173' '40017' '40027' '40031' '40037' '40101' '40109' '40119' '40125'
 '40131' '40143' '40145' '41003' '41005' '41017' '41019' '41029' '41033'
 '41035' '41039' '41043' '41047' '41051' '41053' '41059' '41067' '41071'
 '42001' '42003' '42005' '42007' '42011' '42013' '42017' '42019' '42021'
 '42025' '42027' '42029' '42033' '42039' '42041' '42043' '42045' '42049'
 '42051' '42055' '42063' '42069' '42071' '42073' '42075' '42077' '42079'
 '42081' '42085' '42089' '42091' '42095' '42097' '42101' '42107' '42111'
 '42125' '42129' '42133' '44003' '44005' '44007' '44009' '45003' '45007'
 '45013' '45015' '45019' '45035' '45041' '45045' '45047' '45051' '45055'
 '45057' '45059' '45063' '45073' '45075' '45077' '45079' '45083' '45085'
 '45091' '46083' '46099' '46103' '47001' '47009' '47011' '47037' '47059'
 '47063' '47065' '47093' '47113' '47119' '47125' '47141' '47147' '47149'
 '47155' '47157' '47163' '47165' '47179' '47187' '47189' '48005' '48021'
 '48027' '48029' '48037' '48039' '48041' '48061' '48085' '48091' '48099'
 '48113' '48121' '48135' '48139' '48141' '48157' '48167' '48181' '48183'
 '48187' '48201' '48203' '48209' '48213' '48215' '48221' '48231' '48245'
 '48251' '48257' '48291' '48303' '48309' '48329' '48339' '48355' '48361'
 '48367' '48375' '48381' '48397' '48409' '48423' '48427' '48439' '48441'
 '48451' '48453' '48469' '48471' '48479' '48485' '48491' '48497' '49005'
 '49011' '49035' '49045' '49049' '49053' '49057' '50007' '51003' '51013'
 '51015' '51019' '51041' '51059' '51061' '51069' '51085' '51087' '51095'
 '51107' '51121' '51153' '51161' '51165' '51177' '51179' '51199' '51510'
 '51550' '51650' '51680' '51700' '51710' '51740' '51760' '51770' '51800'
 '51810' '53005' '53007' '53009' '53011' '53015' '53021' '53025' '53027'
 '53029' '53033' '53035' '53041' '53045' '53053' '53057' '53061' '53063'
 '53067' '53073' '53077' '54003' '54011' '54033' '54039' '54061' '54081'
 '54107' '55009' '55017' '55025' '55027' '55035' '55039' '55055' '55059'
 '55063' '55071' '55073' '55079' '55087' '55089' '55097' '55101' '55105'
 '55109' '55111' '55117' '55127' '55131' '55133' '55139' '55141' '56021'
 '56025']